### PR TITLE
fix: Fixing otsar hayal scraper

### LINKED ISSUE #583: Otsar hayal scraper is broken
The scraper returns duplicates transaction and missing fields in some cases.
I know that 'otsar hayal' changed their website couple of months ago...

I'm using this in my own app and manage to fix it in my fork
it's seems that the problem is here: `parseTransactionPage`
https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/scrapers/otsar-hahayal.ts#L97

I changed it to this and it seems to work great
```
async function parseTransactionPage(page: Page) {
  const tdsValues = await pageEvalAll(page, '#dataTable077 tbody tr', [], (trs) => {
    return trs.map((el) => ({
      date: el.querySelector('.date').innerText,
      description: el.querySelector('.reference').innerText,
      credit: el.querySelector('.credit').innerText,
      debit: el.querySelector('.debit').innerText,
      balance: el.querySelector('.balance').innerText,
    }));
  });

  // first row is total balance info, not a transaction
  return tdsValues.splice(1);
}
```

### PR DESCRIPTION
**Pull request by baaraak**
#583
This change will fix Otsar-Hayal scraper.

closes #583

### CODE REVIEW

File: src/scrapers/otsar-hahayal.ts [hunk 1]
```diff
@@ -94,42 +94,19 @@ function convertTransactions(txns: ScrapedTransaction[]): Transaction[] {
 }
 
 async function parseTransactionPage(page: Page): Promise<ScrapedTransaction[]> {
-  const tdsValues = await pageEvalAll<{ classList: string, innerText: string}[]>(page, '#dataTable077 tbody tr td', [], (tds) => {
-    return (tds as HTMLElement[]).map((td) => ({
-      classList: td.getAttribute('class') || '',
-      innerText: (td).innerText || '',
+  const tdsValues = await pageEvalAll(page, '#dataTable077 tbody tr', [], (trs) => {
+    return (trs).map((el) => ({
+      date: (el.querySelector('.date') as HTMLElement).innerText,
```
Comment (baaraak) [inline src/scrapers/otsar-hahayal.ts:99]: Not sure if there is a better way to define this type `HTMLElement` in one place instead of in each field.
If there is, Let me know and I will fix it...

Comment (esakal) [reply src/scrapers/otsar-hahayal.ts:99]: I think it is ok like that for this scenario

**Review by esakal — APPROVED** [review]
@baaraak Thanks for your contribution. I don't have account there so I'm counting on your tests. Code-wise it seems valid so I will merge it to master

**Comment by esakal** [comment]
Hi @baaraak  sorry for the delay, see my comment here https://github.com/eshaham/israeli-bank-scrapers/pull/593#issuecomment-872484714 which will also affect your PR.
