### PR TITLE
fix(cal): authorization not being set

### LINKED ISSUE #963: Cal: Unexpected end of JSON input
Cal scraping is failing due to the following issue: Unexpected end of JSON input
I have found the issue.
The getAuthorizationHeader function is called before the token is set, causing a null value to be set as the token.
I have a fix, just want to confirm that others are experiencing this before opening a PR?

### PR DESCRIPTION
**Pull request by DavidConnack**
Changes:

* Fixed #963 

By fetching the auth header later in the process, it is populated and not null

### CODE REVIEW

**Comment by DavidConnack** [comment]
I agree its not a perfect fix, but as with all things scraping, its a game of whackamole.
We could add a sleep, but in my testing this consistently fixed the issue (for now)

File: src/scrapers/visa-cal.ts [hunk 1]
```diff
@@ -411,9 +411,9 @@ class VisaCalScraper extends BaseScraperWithBrowser<ScraperSpecificCredentials>
     const startMoment = moment.max(defaultStartMoment, moment(startDate));
     debug(`fetch transactions starting ${startMoment.format()}`);
 
-    const Authorization = await this.getAuthorizationHeader();
     const cards = await this.getCards();
     const xSiteId = await this.getXSiteId();
+    const Authorization = await this.getAuthorizationHeader();
```
Comment (baruchiro) [inline src/scrapers/visa-cal.ts]: You can see how `this.getCards` using the `waitUntil` utility to wait until the value is there (or timeout).

You can use the same approach, and to save time, call both `getCards` and `getAuthorizationHeader` with `Promise.all`.

Comment (DavidConnack) [reply src/scrapers/visa-cal.ts]: @baruchiro thanks for the feedback done.
I found an issue with the base-scraper:
```
      const success = scrapeResult && scrapeResult.success === true;
      await this.terminate(success);
```
The terminate breaks the tests, but I don't think its related to this fix.
It seems to be related to this issues: #952

**Comment by baruchiro** [comment]
I tested and it works, but I want to wait for #968

**Comment by DavidConnack** [comment]
Thanks @baruchiro

**Comment by ValYouW** [comment]
This doesn't seem to solve the issue in my case, maybe I didn't port the code correctly (I ported it directly to the transpiled javascript, not via typescript).

What happens is that `getFromSessionStorage` returns the following "truthy" value:
```js
{ auth: { calConnectToken: null, timestamp: null } }
```

This causes `waitUntil` to return although `authModule.auth.calConnectToken` is `null`.

**Comment by DavidConnack** [comment]
@baruchiro 
Can you point me in the direction of them? I checked in the helpers, but I couldnt see anything relevant.
Thanks
