### PR TITLE
fix(isracard): attempt to defeat block-automation

### LINKED ISSUE #970: Isracard response `Unexpected token 'B', "Block Automation" is not valid JSON`
i got the response `Unexpected token 'B', "Block Automation" is not valid JSON` when trying to scrap more than 1 isracard cards in a session

manager function:
```
  cardConfig.forEach((card) => {
    promises.push(scrape(card, nextMonth))
  })

  return await Promise.all(promises)
```

scrapping function:
```
const scraper = createScraper({
    companyId: card.companyId,
    combineInstallments: true,
    showBrowser: card.showBrowser,
    startDate: scrapStartDate
  })

  const result = await scraper.scrape({
    id: card.username,
    username: card.username,
    password: card.password,
    card6Digits: card.lastDigits,
    num: card.userCode,
    userCode: card.userCode
  })
  const { success, errorType, errorMessage } = result

  if (!success) {
    throw new Error(`Error: ${errorType} - ${errorMessage}`)
  }

```

package version: `6.2.0`

### PR DESCRIPTION
**Pull request by daniel-hauser**
Fixes #970 by converting parallel network requests to sequential using runSerial.
I also Introduced a new opt-in feature `isracard-amex:skipAdditionalTransactionInformation` to allow skipping additional transaction details without globally disabling the `additionalTransactionInformation` options

Closes #993

### CODE REVIEW

File: src/scrapers/base-isracard-amex.ts [hunk 1]
```diff
@@ -251,30 +259,21 @@ async function fetchTransactions(
...
 async function getExtraScrapTransaction(
   page: Page,
   options: CompanyServiceOptions,
   month: Moment,
   accountIndex: number,
   transaction: Transaction,
 ): Promise<Transaction> {
-  const dataUrl = getTransactionExtraDetails(options.servicesUrl, month, accountIndex, transaction);
-  const data = await fetchGetWithinPage<ScrapedTransactionData>(page, dataUrl);
+  const url = new URL(servicesUrl);
```
Comment (daniel-hauser) [inline src/scrapers/base-isracard-amex.ts]:
```suggestion
  const url = new URL(options.servicesUrl);
```

File: src/scrapers/base-isracard-amex.ts [hunk 2]
```diff
@@ -286,40 +285,47 @@ async function getExtraScrapTransaction(
...
+      txns.push(...updatedTxns);
+    }
+    accounts.push({ ...account, txns });
+  }
+
   return accounts.reduce((m, x) => ({ ...m, [x.accountNumber]: x }), {});
 }
 
-function getExtraScrap(
+async function getAdditionalTransactionInformation(
```
Comment (baruchiro) [inline src/scrapers/base-isracard-amex.ts:315]: You did an important work here with reducing the functions with their confusing names
