### PR TITLE
fix: Visa Cal - add missing transactions and fix the amount sign in case of credit (refund)

### LINKED ISSUE #807: visa-cal scraper incorrectly parsing credits
I use moneyman. When a transaction is a credit, I'm seeing the scraper return a negative `chargedAmount` and a positive `originalAmount`.

I expect them both to be positive in case of a credit (are there any cases where they should have a different sign?)

I'm seeing this only with visa-cal, the other scrapers seem fine.

### PR DESCRIPTION
**Pull request by itamarco**
Fixes #807 
This PR fix 2 issues with Visa Cal scraper:

1. In case of credits (refund) the "amount" field is still in minus instead of plus.
2. The scraper ignored the "immidiateDebits" field that may contains additional transactions

image

### CODE REVIEW

File: src/scrapers/visa-cal.ts [hunk 1]
```diff
@@ -193,11 +199,6 @@ function convertParsedDataToTransactions(parsedData: CardTransactionDetails[]):
       let chargedAmount = transaction.amtBeforeConvAndIndex * (-1);
       let originalAmount = transaction.trnAmt * (-1);
 
-      if (transaction.trnTypeCode === trnTypeCode.credit) {
-        chargedAmount = transaction.amtBeforeConvAndIndex;
-        originalAmount = transaction.trnAmt;
-      }
-
```
Comment (itamarco) [inline src/scrapers/visa-cal.ts:200]: Not needed anymore. sign is already correct for `chargedAmount`

**Review by esakal — APPROVED** [review]

**Comment by esakal** [comment]
@itamarco  thanks for the contribution.
@eshaham can you check why the checks are on status waiting? I cannot merge the PR

**Comment by esakal** [comment]
@eshaham I managed to merge a PR #811 but this one is still stuck on the checks. Please merge. hopefully new PRs will work also for me
