### PR TITLE
[hapoalim] Fix balance error for closed accounts

### LINKED ISSUE #640: [hapoalim] Fetch error
# Description
The poalim scraper stops to work with a `TypeError: Failed to fetch` error.
After investigating, seems like the endpoint added in #576 redirects to itself if the account is closed- causing the error.

# Solution
A possible solution is to wrap the balance logic in a try-catch and fallback the balance to undefined (the value before the #576 PR) if the account is closed.

# Error log
Adding the following code to `fetchData()`
```javascript
      this.page
      .on('response', response => {
        if (response.status() === 302) {
          console.log(`[response]${response.status()} ${response.url()}\n -> Location:`, response.headers()['location']);
        }
      })
      .on('request', request => {
        if(request.url().includes('balanceAndCreditLimit')) {
          console.log('[request]', `${request.url()}`);
        }
      })
      .on('requestfailed', request => {
        if (request.url().includes('balanceAndCreditLimit')) {
          console.log('[requestfailed]', `${request.failure().errorText} ${request.url()}`);
        }
      });
```

I got this log:
```
  [request] https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [request] https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?partyCurrentAccount=[REMOVED]&lang=he
  [request] https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [response]302 https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
   -> Location: https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [request] https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [response]302 https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
   -> Location: https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [request] https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [requestfailed] net::ERR_HTTP2_PROTOCOL_ERROR https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  Error: Evaluation failed: TypeError: Failed to fetch
      at ExecutionContext._evaluateInternal (/workspaces/money/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async ExecutionContext.evaluate (/workspaces/money/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
      at async fetchAccountData (/workspaces/money/node_modules/israeli-bank-scrapers/src/scrapers/hapoalim.ts:154:35)
      at async HapoalimScraper.scrape (/workspaces/money/node_modules/israeli-bank-scrapers/src/scrapers/base-scraper.ts:159:24)
      at async getAccountTransactions (file:///workspaces/money/src/data/scrape.ts:26:20)
      at async scrapeAccount (file:///workspaces/money/src/data/index.ts:64:18)
      at async scrapeAccounts (file:///workspaces/money/src/data/index.ts:27:20)
      at async Promise.all (index 0)
      at async run (file:///workspaces/money/src/index.ts:15:23)
```

### PR DESCRIPTION
**Pull request by daniel-hauser**
- Fixes #640 by skipping the balance checking for closed accounts.
- Added logs for failed requests.
- Added logs for hapoalim scraper.
- Separated code functions for ease of reading.

### CODE REVIEW

**Comment by daniel-hauser** [comment]
@eshaham can you review my PR?
thanks!

**Comment by esakal** [comment]
@daniel-hauser it looks legit but I don't have Hapoalim account to double check it. If anyone with Hapoalim account want to try it out before we release it please drop a comment

File: src/scrapers/hapoalim.ts [hunk 1]
```diff
@@ -147,21 +168,20 @@ async function fetchAccountData(page: Page, baseUrl: string, options: ScaperOpti
...
-    const accountNumber = `${accountsInfo[accountIndex].bankNumber}-${accountsInfo[accountIndex].branchNumber}-${accountsInfo[accountIndex].accountNumber}`;
-
-    const balanceAndCreditLimitUrl = `${apiSiteUrl}/current-account/composite/balanceAndCreditLimit?accountId=${accountNumber}&view=details&lang=he`;
-    const balanceAndCreditLimit = await fetchGetWithinPage(page, balanceAndCreditLimitUrl) as BalanceAndCreditLimit;
-    const balance: number = balanceAndCreditLimit?.currentBalance;
 
-    const txnsUrl = `${apiSiteUrl}/current-account/transactions?accountId=${accountNumber}&numItemsPerPage=150&retrievalEndDate=${endDateStr}&retrievalStartDate=${startDateStr}&sortCode=1`;
-    const txnsResult = await fetchPoalimXSRFWithinPage(page, txnsUrl, '/current-account/transactions');
-    let txns: Transaction[] = [];
+  for (const account of accountsInfo) {
```
Comment (esakal) [inline src/scrapers/hapoalim.ts:172]: out of curiosity, how does it works for you? await doesn't work in for...of... unless I'm mistaken
CleanShot 2021-12-29 at 21 16 35@2x


CleanShot 2021-12-29 at 21 16 43@2x

Comment (esakal) [reply src/scrapers/hapoalim.ts:172]: @daniel-hauser see comment above

Comment (daniel-hauser) [reply src/scrapers/hapoalim.ts:172]: @esakal You probably run the code in a node version that doesn't support top level awaits, you can put the for loop inside a async function and it will work.

**Review by esakal — APPROVED** [review]
