### PR TITLE
Fix leumi card rebranding

### LINKED ISSUE #179: Leumi Card scrapper stopped working
I get the following error. Seems like it logs in ok but the return value after login is not recgnized:
Leumi Card: START_SCRAPING
Leumi Card: INITIALIZING
Leumi Card: LOGGING_IN
Leumi Card: TERMINATING
Leumi Card: END_SCRAPING
success: false
error type: generic
error: unexpected login result "undefined"
Error: unexpected login result "undefined"
    at /Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:62:11
    at Generator.next (<anonymous>)
    at step (/Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:47:191)
    at /Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:47:361
(node:7970) UnhandledPromiseRejectionWarning: Error: unexpected login result "undefined"
    at /Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:62:11
    at Generator.next (<anonymous>)
    at step (/Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:47:191)
    at /Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:47:361
(node:7970) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7970) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### PR DESCRIPTION
**Pull request by esakal**
# Motivation
1. Fix Leumi Card scraper that was broken by the new website (the max rebranding)
2. Fix recognition of invalid user/password flow
3. Fix unexpected error that happens when scraping more then multiple months. It doesn't happen all the times but still quite frequently

# Infrastructure adjustments

## Navigation > waitForRedirect
To support the new leumi card login flow, `waitForRedirect` method was adjusted to optionally ignore redirect if needed

##  Compare login target with case insensitive
The leumi card site might redirect to same page with different case sensitive when typing invalid password

fixes #179

### CODE REVIEW

**Comment by esakal** [comment]
@eshaham can you please review this and merge/deploy if possible? The Leumi card scraper will not work anymore without those adjustments :)

File: src/helpers/navigation.js [hunk 1]
```diff
@@ -21,12 +21,13 @@ export async function getCurrentUrl(page, clientSide = false) {
...
 
-export async function waitForRedirect(page, timeout = 20000, clientSide = false) {
+export async function waitForRedirect(page, timeout = 20000, clientSide = false, ignoreList = []) {
   const initial = await getCurrentUrl(page, clientSide);
+
   try {
     await waitUntil(async () => {
       const current = await getCurrentUrl(page, clientSide);
-      return current !== initial;
+      return current !== initial && ignoreList.indexOf(current) === -1;
```
Comment (eshaham) [inline src/helpers/navigation.js]: @esakal `&& !ignoreList.includes(current)` is more elegant

File: src/scrapers/leumi-card.js [hunk 2]
```diff
@@ -286,17 +287,18 @@ async function fetchTransactions(browser, options, navigateToFunc) {
...
-  const task = fetchTransactionsForMonth(browser, navigateToFunc);
+  const task = () => fetchTransactionsForMonth(browser, navigateToFunc);
   allTasks.push(task);
 
-  const allTasksResults = await Promise.all(allTasks);
-  const allResults = allTasksResults.reduce((obj, result) => {
-    return addResult(obj, result);
-  }, {});
+  let allResults = {};
+  for (const task of allTasks) {
```
Comment (eshaham) [inline src/scrapers/leumi-card.js]: @esakal if we cannot fetch results asynchronously, we might as well fetch them within the loops 👆 
(so no need to create an array of tasks).

File: src/helpers/navigation.js (hunk 1 above)
Comment (esakal) [reply src/helpers/navigation.js]: 👍

File: src/scrapers/leumi-card.js (hunk 2 above)
Comment (esakal) [reply src/scrapers/leumi-card.js]: sure, I tried to keep changes to minimum but I agree it will simplify the logic.

btw, although before this PR we opened all browsers in parallel, we still scraped each one of them in a sequence thus I don't expect a noticeable performance hit

Comment (eshaham) [reply src/scrapers/leumi-card.js]: 👍
